### ISSUE TITLE
Trying to use this with Sapper

### ISSUE THREAD

**Issue by hsb-tonmoy** [techlab23/ckeditor5-svelte#1]
I copied and pasted the sample code you showed in the README and this is what I get when I run **npm run dev**:

`A ton of gibberish - server crashed - `

![image](https://user-images.githubusercontent.com/35843150/114805746-87ca9d00-9d71-11eb-89f7-c5c431c8db34.png)

**Comment by niraj-gawande** [comment]
How do you managed to integrate it into sapper ?  I am facing the same issue.
